export const mrpQueryKeys = {
    products: 'mrp.products',
    productsList: (page: number, limit: number) => `mrp.products.${page}.${limit}`,
    product: (id: string) => `mrp.product.${id}`,
    suppliers: 'mrp.suppliers',
    suppliersList: (page: number, limit: number) => `mrp.suppliers.${page}.${limit}`,
    supplier: (id: string) => `mrp.supplier.${id}`,
    supplierMaterials: (id: string) => `mrp.supplier.materials.${id}`,
    rawMaterials: 'mrp.raw-materials',
    rawMaterialsList: (page: number, limit: number, search: string) => `mrp.raw-materials.${page}.${limit}.${search || ''}`,
    rawMaterial: (id: string) => `mrp.raw-material.${id}`,
    rawMaterialSuppliers: (id: string) => `mrp.raw-material.suppliers.${id}`,
    warehouses: 'mrp.warehouses',
    warehouse: (id: string) => `mrp.warehouse.${id}`,
    purchaseOrders: 'mrp.purchase-orders',
    purchaseOrdersList: (page: number, limit: number, status?: string, supplierId?: string) =>
        `mrp.purchase-orders.${page}.${limit}.${status || ''}.${supplierId || ''}`,
    purchaseOrder: (id: string) => `mrp.purchase-order.${id}`,
    productionOrders: 'mrp.production-orders',
    productionOrdersList: (page: number, limit: number) => `mrp.production-orders.${page}.${limit}`,
    productionOrder: (id: string) => `mrp.production-order.${id}`,
    productionBatches: (id: string) => `mrp.production-batches.${id}`,
    productionRequirements: (id: string) => `mrp.production-requirements.${id}`,
    operationalConfig: 'mrp.operational-config',
    qualityNonConformities: 'mrp.quality.non-conformities',
    qualityCapas: 'mrp.quality.capa-actions',
    qualityAuditEvents: 'mrp.quality.audit-events',
    qualityTechnovigilanceCases: 'mrp.quality.technovigilance-cases',
    qualityRecalls: 'mrp.quality.recalls',
    qualityRegulatoryLabels: 'mrp.quality.regulatory-labels',
    qualityComplianceDashboard: 'mrp.quality.compliance-dashboard',
    qualityRiskControls: 'mrp.quality.risk-controls',
    qualityTrainingEvidence: 'mrp.quality.training-evidence',
    qualityDocuments: 'mrp.quality.documents',
    qualityActiveDocuments: (process: string) => `mrp.quality.documents.active.${process}`,
};
